[package]
name = "wave_func_collapse_3d"
version = "0.1.0"
authors = ["minujeong <minu.hanwool@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.39.1"
glium = "*"
